[project]
name = "ex01-loading"
version = "0.1.0"
description = "Dependency validation and data visualization exercise"
authors = [{ name = "chrilomb" }]
requires-python = ">=3.10,<3.13"
dependencies = [
	"pandas==2.1.0",
	"requests==2.31.0",
	"matplotlib==3.7.2",
	"pybind11>=2.12",
	"numpy==1.22.4",
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
